apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: {{ argocd_namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ argocd_domain }}`)
      services:
        - name: argocd-server
          port: 80
  tls:
    secretName: {{ argocd_tls_secret }}
