[rke2_servers]
master ansible_host=192.168.1.42

[all:vars]
ansible_user=devopstatu
ansible_ssh_private_key_file=/Users/tatuzinho/Documents/tatulab/devopstatu
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
