apiVersion: v1
kind: Service
metadata:
  name: demo-spring-boot
  labels:
    app: demo-spring-boot
spec:
  type: ClusterIP
  selector:
    app: demo-spring-boot
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
