[rke2_servers]
vm-control1 ansible_host=192.168.1.42
vm-control2 ansible_host=192.168.1.43
vm-control3 ansible_host=192.168.1.44

[rke2_agents]
vm-work1 ansible_host=192.168.1.45
vm-work2 ansible_host=192.168.1.46
vm-work3 ansible_host=192.168.1.47
vm-work4 ansible_host=192.168.1.48

[all:vars]
ansible_user                 = devopstatu
ansible_ssh_private_key_file = /Users/tatuzinho/Documents/tatulab/iac-tatulab/controlplane-install/devopstatu
ansible_ssh_common_args      = '-o StrictHostKeyChecking=no'

k8s_endpoint_ip  = 192.168.1.41
k8s_endpoint_dns = kube.tatulab.com.br
rke2_version     = latest
rke2_cni         = calico
metallb_pool_name = pool-tatulab
metallb_ip_range  = 192.168.1.70-192.168.1.95
